name: '@acai build'

on:
  pull_request:
  push:
    branches: [ production, development ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: https://registry.npmjs.org/

      - name: Rush CLI
        run: npm install -g @microsoft/rush

      - name: Rush Install
        uses: advancedcsg-open/actions-rush@v1.0.1

      - name: Rush Build
        run: rush lint

      - name: Rush Build
        run: rush build