name: '@acai build'

on:
  pull_request:
  push:
    branches: [ production, development ]
  release:
    types: [created, edited, prereleased, published]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: https://registry.npmjs.org/

      - name: Rush CLI
        run: npm install -g @microsoft/rush

      - name: Global ts-node-dev
        run: npm install -g ts-node-dev

      - name: Rush Install
        uses: advancedcsg-open/actions-rush@v1.4.5

      - name: Audit dependencies
        run: rush audit

      - name: Lint codebase
        run: rush lint

      - name: Build packages
        run: rush build

      - name: Test packages
        run: rush test
      
      - name: Publish packages
        uses: ./.github/workflows/delivery@v1
        if: ${{ github.event.release.body!= "" && success() }}
        with:
          - body: ${{ github.event.release.body }}
        secrets:
          token: ${{ secrets.NPM_TOKEN }}