name: '@acai build'

on:
  pull_request:
  push:
    branches: [ production, development ]
  release:
    types: [ published ]

jobs:
  setup:
    name: Setup node and environment
    uses: darklight9811/modules/.github/workflows/setup-env.yml@development

  audit:
    name: Audit for vulnerabilities
    needs: setup
    runs-on: ubuntu-latest
    uses: darklight9811/modules/.github/workflows/setup-env.yml@development
    steps:
      - run: rush audit

  lint:
    name: Lint code for standarlization
    needs: setup
    runs-on: ubuntu-latest
    uses: darklight9811/modules/.github/workflows/setup-env.yml@development
    steps:
      - run: rush lint

  build:
    name: Build all packages
    needs: [lint, audit]
    runs-on: ubuntu-latest
    uses: darklight9811/modules/.github/workflows/setup-env.yml@development
    steps:
      - run: rush build

  test_1:
    name: Test general packages
    needs: build
    runs-on: ubuntu-latest
    uses: darklight9811/modules/.github/workflows/setup-env.yml@development
    steps:
      - run: rush test

  test_2:
    name: Test database packages
    needs: build
    runs-on: ubuntu-latest
    uses: darklight9811/modules/.github/workflows/setup-env.yml@development
    steps:
      - run: echo 'implement database tests'
      
  publish:
    name: Publish packages
    needs: [build, test_1, test_2]
    runs-on: ubuntu-latest
    uses: darklight9811/modules/.github/workflows/setup-env.yml@development
    if: ${{ github.event.release.body != '' && success() }}
    steps:
      - name: Publish packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          RELEASE: ${{ github.event.release.body }}
        run: rush bump
