name: '@acai build'

on:
  pull_request:
  push:
    branches: [ production, development ]
  release:
    types: [ published ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: https://registry.npmjs.org/

      - name: Rush CLI
        run: npm install -g @microsoft/rush

      - name: Global ts-node-dev
        run: npm install -g ts-node-dev

      - name: Rush Install
        uses: advancedcsg-open/actions-rush@v1.4.5

      - name: Upload enviromnent
        uses: actions/upload-artifact@v2
        with:
          name: env

  audit:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: env
      - run: rush audit

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: env
      - run: rush lint

  build:
    needs: [lint, audit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: env
      - run: rush build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: env
      - run: rush test
      
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: env
      - name: Publish packages
        if: ${{ github.event.release.body != '' && success() }}
        uses: ./.github/workflows/delivery@master
        with:
          body: "${{ github.event.release.body }}"
          token: "${{ secrets.NPM_TOKEN }}"
