name: '@acai build'

on:
  pull_request:
  push:
    branches: [ production, development ]
  release:
    types: [ published ]

jobs:
  setup:
    name: Setup node and environment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: AcaiJS
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: https://registry.npmjs.org/

      - name: Cache node modules
        id: cacheNode
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Rush CLI
        if: steps.cacheNode.outputs.cache-hit != 'true'
        run: npm install -g @microsoft/rush

      - name: Global ts-node-dev
        if: steps.cacheNode.outputs.cache-hit != 'true'
        run: npm install -g ts-node-dev

      - name: Rush Install
        uses: advancedcsg-open/actions-rush@v1.4.5

  audit:
    name: Audit for vulnerabilities
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Rush Install
        uses: advancedcsg-open/actions-rush@v1.4.5

      - name: Rush CLI
        run: npm install -g @microsoft/rush
          
      - run: rush audit

  lint:
    name: Lint code for standarlization
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Rush Install
        uses: advancedcsg-open/actions-rush@v1.4.5

      - name: Rush CLI
        run: npm install -g @microsoft/rush
          
      - run: rush lint --fix

  build:
    name: Build all packages
    needs: [audit, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Rush Install
        uses: advancedcsg-open/actions-rush@v1.4.5
        with:
          build: true

  test_1:
    name: Test general packages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Rush Install
        uses: advancedcsg-open/actions-rush@v1.4.5
        with:
          build: true

      - name: Rush CLI
        run: npm install -g @microsoft/rush

      - name: Global ts-node-dev
        run: npm install -g ts-node-dev
          
      - run: rush test

  test_2:
    name: Test database packages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Rush Install
        uses: advancedcsg-open/actions-rush@v1.4.5
        with:
          build: true

      - name: Rush CLI
        run: npm install -g @microsoft/rush

      - name: Global ts-node-dev
        run: npm install -g ts-node-dev
          
      - run: echo 'implement database tests'

  publish:
    name: Publish release packages
    needs: [test_1, test_2]
    runs-on: ubuntu-latest
    if: ${{ github.event.release.body != '' && success() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Rush Install
        uses: advancedcsg-open/actions-rush@v1.4.5

      - name: Rush CLI
        run: npm install -g @microsoft/rush
          
      - name: Publish packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          RELEASE: ${{ github.event.release.body }}
        run: rush bump
