name: 'Validation'

on:
  pull_request: 
    branches: [ development ]

jobs:
  setup:
    name: Setup node and environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Rush Install
        uses: advancedcsg-open/actions-rush@v1.4.5

  audit:
    name: Audit for vulnerabilities
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Rush Install
        uses: advancedcsg-open/actions-rush@v1.4.5
          
      - run: node common/scripts/install-run-rush.js audit

  lint:
    name: Lint code for standarlization
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Rush Install
        uses: advancedcsg-open/actions-rush@v1.4.5
          
      - run: node common/scripts/install-run-rush.js lint

  analyze:
    name: Analyze code for vulnerabilities
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: 'javascript'

    - name: Autobuild
      uses: github/codeql-action/autobuild@v1

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1


  build:
    name: Build all packages
    needs: [audit, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache builds
        id: cacheBuilds
        uses: actions/cache@v2
        env:
          cache-name: cache-builds
        with:
          path: ./packages/**/dist
          key: ${{ runner.os }}-${{ env.cache-name }}
          restore-keys: ${{ runner.os }}-${{ env.cache-name }}

      - name: Rush Install
        uses: advancedcsg-open/actions-rush@v1.4.5
        with:
          build: true

  test_1:
    name: Test general packages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Rush Install
        uses: advancedcsg-open/actions-rush@v1.4.5

      - name: Cache builds
        id: cacheBuilds
        uses: actions/cache@v2
        env:
          cache-name: cache-builds
        with:
          path: ./packages/**/dist
          key: ${{ runner.os }}-${{ env.cache-name }}
          restore-keys: ${{ runner.os }}-${{ env.cache-name }}
          
      - name: Test
        run: node common/scripts/install-run-rush.js test

  test_2:
    name: Test database packages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Rush Install
        uses: advancedcsg-open/actions-rush@v1.4.5

      - name: Cache builds
        id: cacheBuilds
        uses: actions/cache@v2
        env:
          cache-name: cache-builds
        with:
          path: ./packages/**/dist
          key: ${{ runner.os }}-${{ env.cache-name }}
          restore-keys: ${{ runner.os }}-${{ env.cache-name }}
          
      - uses: getong/mariadb-action@v1.1
        with:
          mysql user: ${{ secrets.DATABASE_USER }}
          mysql password: ${{ secrets.DATABASE_PASSWORD }}
          mysql database: acai_query
          
      - run: echo 'implement database tests'

  verify_publish:
    name: Verify version bump
    needs: [test_1, test_2]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Rush Install
        uses: advancedcsg-open/actions-rush@v1.4.5

      - name: Cache builds
        id: cacheBuilds
        uses: actions/cache@v2
        env:
          cache-name: cache-builds
        with:
          path: ./packages/**/dist
          key: ${{ runner.os }}-${{ env.cache-name }}
          restore-keys: ${{ runner.os }}-${{ env.cache-name }}
          
      - name: Verify changes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          PULL_REQUEST: ${{ github.event.number }}
        run: node common/scripts/install-run-rush.js verify
          
      - name: Verify publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          PULL_REQUEST: ${{ github.event.number }}
        run: node common/scripts/install-run-rush.js duplicate